# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 13:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400)),
                ('priority', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('A', 'Active'), ('P', 'Pending'), ('W', 'Waiting'), ('D', 'Done'), ('C', 'Canceled')], default='W', max_length=1)),
                ('createdate', models.DateTimeField(blank=True, null=True, verbose_name='date')),
                ('duedate', models.DateTimeField(blank=True, null=True, verbose_name='date')),
                ('actiondate', models.DateTimeField(blank=True, null=True, verbose_name='date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
