# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20160318_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='mothertask',
            field=models.ForeignKey(blank=True, default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Task'),
        ),
    ]
